### ISSUE TITLE
error: ‘memcpy’ was not declared in this scope

### ISSUE THREAD

**Issue by lukad** [jbendig/InvGrid#8]
Types.h:61:2: error: ‘memcpy’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
Types.h should include string.h

**Comment by stevenroose** [comment]
I get the same error. Anyone got this resolved?

**Comment by jbendig** [comment]
I fixed this issue because it was quick. I'm not sure why I didn't see it when it was reported in 2012, but that shows how long this project has been abandoned. Honestly @stevenroose, I'm not sure if this is compatible with newer versions of Minecraft. You might want to find an alternative that is actively maintained.

**Comment by stevenroose** [comment]
I did. There isn't anything that can read playerstate .dat files and that
works on Linux.

**Comment by stevenroose** [comment]
So many thanks for this, I will give it a try sometime!
